### ISSUE TITLE
Project no longer builds

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#556]
**Describe the bug**
`yarn serve` or `make build` boith result in errors:

**To Reproduce**
* Freshly clone the repo
* Run `yarn install`
* Run `yarn serve` or `make build` 

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser N/A
 - Version N/A

**Additional context**
Exact error:

```
~/repos/corteza-webapp-compose$  yarn run serve
yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...
10% building 2/5 modules 3 active /home/anon/repos/corteza-webapp-compose/node_modules/webpack/hot/dev-server.jsError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/anon/repos/corteza-webapp-compose/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/anon/repos/corteza-webapp-compose/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/anon/repos/corteza-webapp-compose/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/anon/repos/corteza-webapp-compose/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/anon/repos/corteza-webapp-compose/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/anon/repos/corteza-webapp-compose/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/anon/repos/corteza-webapp-compose/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Maybe this has to do with the recent open-ssl 3 vulnerability?

https://www.zdnet.com/article/openssl-warns-of-critical-security-vulnerability-with-upcoming-patch/

**Comment by skamensky** [comment]
Workaround as found here is https://github.com/webpack/webpack/issues/14532#issuecomment-947012063

`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by darh** [comment]
Resolved.

**Comment by skamensky** [comment]
What was done to resolve this?

I'm still undergoing this problem and need to change add that environment variable as a workaround.

**Comment by darh** [comment]
🤷‍♂️  Was under the impression that that did the trick for you.

Leaving it open then, maybe someone else can take a look into it.
