### ISSUE TITLE
Reporter not responsive - performance and memory footprint issue

### ISSUE THREAD

**Issue by skamensky** [cortezaproject/corteza#778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version of Corteza

2023.3.0-dev.1

### Current Behavior

Memory usage is 4gb+ and page is completely not responsive. The report is simple. It's one load and a table showing the loaded data source. There are no filters.

### Anything else?

Memory usage:

![image](https://user-images.githubusercontent.com/19151369/212303676-88379f03-bbfd-4281-ac55-5129b898fbfa.png)

CPU profile:
[Profile-20230113T125305.json.gz](https://github.com/cortezaproject/corteza/files/10410843/Profile-20230113T125305.json.gz)

**Comment by skamensky** [comment]
Here is a server runtime error that happened before the performance issue popped up:
```================================================================================
--------------------------------------------------------------------------------
goroutine 96630 [running]:
runtime/debug.Stack()
  /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
  /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/debug/stack.go:16 +0x19
github.com/cortezaproject/corteza/server/pkg/api/server.panicRecovery({0x26ec830, 0xc000f59e80}, {0x26ea090, 0xc0005f48c0})
  /home/runner/work/corteza/corteza/server/pkg/api/server/middleware.go:43 +0x111
panic({0x1d1cb80, 0x3633730})
  /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
github.com/getsentry/sentry-go/http.(*Handler).recoverWithSentry(0xc000d738c0, 0x0?, 0xc000ebdf00)
  /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.13.0/http/sentryhttp.go:117 +0xf0
panic({0x1d1cb80, 0x3633730})
  /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:884 +0x212
github.com/cortezaproject/corteza/server/pkg/dal.Pipeline.LinkSteps({0xc000e54930, 0x1, 0x1})
  /home/runner/work/corteza/corteza/server/pkg/dal/pipeline.go:66 +0x144
github.com/cortezaproject/corteza/server/pkg/dal.(*service).pipelinePrerun(0x0?, {0x26ec8d8, 0xc000c302a0}, {0xc000e54930, 0x1, 0x1})
  /home/runner/work/corteza/corteza/server/pkg/dal/service.go:1122 +0x45
github.com/cortezaproject/corteza/server/pkg/dal.(*service).Run(0x0?, {0x26ec8d8, 0xc000c302a0}, {0xc000e54930?, 0x1?, 0xc000015b58?})
  /home/runner/work/corteza/corteza/server/pkg/dal/service.go:435 +0x37
github.com/cortezaproject/corteza/server/system/service.(*report).Run.func1.1(0xc0002da2a0, {0x26ec8d8, 0xc000c302a0}, 0xc0009a1f58, 0xc0009a2808, 0xc0009a2830, 0xc0009a2818)
  /home/runner/work/corteza/corteza/server/system/service/report.go:354 +0x9d
github.com/cortezaproject/corteza/server/system/service.(*report).Run.func1({0x26ec8d8, 0xc000c302a0}, 0xc0002da2a0, 0xc0009a2798?, {0xc0014177a0, 0x1, 0x4}, 0xc0009a2808?, 0x759da5?, 0xc0009a2818)
  /home/runner/work/corteza/corteza/server/system/service/report.go:372 +0x57c
github.com/cortezaproject/corteza/server/system/service.(*report).Run(0xc0002da2a0, {0x26ec8d8, 0xc000c302a0}, 0x0?, {0xc0014177a0, 0x1, 0x4})
  /home/runner/work/corteza/corteza/server/system/service/report.go:380 +0x11f
github.com/cortezaproject/corteza/server/system/rest.(*Report).Run(0xc001417780?, {0x26ec8d8?, 0xc000c302a0?}, 0xc0009a2920?)
  /home/runner/work/corteza/corteza/server/system/rest/report.go:145 +0x42
github.com/cortezaproject/corteza/server/system/rest/handlers.NewReport.func8({0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/work/corteza/corteza/server/system/rest/handlers/report.go:167 +0x170
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0x1?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/auth.HttpTokenValidator.func1.1({0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/work/corteza/corteza/server/pkg/auth/token_middleware.go:80 +0xba
net/http.HandlerFunc.ServeHTTP(0xc0010c4120?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc000e3c8c0?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x1d03dc0?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0036cc520?)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/chain.go:31 +0x2c
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000d49860, {0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xc0009a2b90?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0009a2b70?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d49860, {0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x355
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x1d03dc0?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0001695f0?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000d49800, {0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xc0009a2d10?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0009a2cf0?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d49800, {0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x355
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x1d03dc0?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0013f1680?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000d49320, {0x7fba2043bcc8, 0xc0015f6340}, 0xc000f97600)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0x38b8348?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/auth.verifier.func1.1({0x7fba2043bcc8, 0xc0015f6340}, 0xc0010de400)
  /home/runner/work/corteza/corteza/server/pkg/auth/token_middleware.go:42 +0x291
net/http.HandlerFunc.ServeHTTP(0x26ea090?, {0x7fba2043bcc8?, 0xc0015f6340?}, 0xc0014d6170?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/api/server.LogResponse.func1({0x26ea090?, 0xc0005f48c0?}, 0xc0010de400)
  /home/runner/work/corteza/corteza/server/pkg/api/server/logger.go:73 +0x114
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0xc0010de500?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/api/server.LogRequest.func1({0x26ea090, 0xc0005f48c0}, 0xc0010de400)
  /home/runner/work/corteza/corteza/server/pkg/api/server/logger.go:50 +0x4a7
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0x38b8348?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/api/server.contextLogger.func1.1({0x26ea090, 0xc0005f48c0}, 0xc0010de300)
  /home/runner/work/corteza/corteza/server/pkg/api/server/logger.go:28 +0x394
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0x38b8348?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/api.DebugToContext.func1.1({0x26ea090, 0xc0005f48c0}, 0xc0010de200)
  /home/runner/work/corteza/corteza/server/pkg/api/debug.go:15 +0x151
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0x26cd658?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x26ea090, 0xc0005f48c0}, 0xc0010de100)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/request_id.go:76 +0x22d
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0x26cd658?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/api.RemoteAddrToContext.func1({0x26ea090, 0xc0005f48c0}, 0xc0010de000)
  /home/runner/work/corteza/corteza/server/pkg/api/ipaddr.go:17 +0x16e
net/http.HandlerFunc.ServeHTTP(0xc0010de000?, {0x26ea090?, 0xc0005f48c0?}, 0xc0010de000?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x26ea090, 0xc0005f48c0}, 0xc0010de000)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/realip.go:35 +0x9e
net/http.HandlerFunc.ServeHTTP(0x26ec8d8?, {0x26ea090?, 0xc0005f48c0?}, 0x38b8348?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/cortezaproject/corteza/server/pkg/locale.DetectLanguage.func1.1({0x26ea090, 0xc0005f48c0}, 0xc000ebdf00)
  /home/runner/work/corteza/corteza/server/pkg/locale/http.go:26 +0x2ad
net/http.HandlerFunc.ServeHTTP(0xc000c60fa0?, {0x26ea090?, 0xc0005f48c0?}, 0xc000ebdf00?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x26ea090, 0xc0005f48c0}, 0xc000ebdf00)
  /home/runner/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc000eb24b0?, {0x26ea090?, 0xc0005f48c0?}, 0xb?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/getsentry/sentry-go/http.(*Handler).handle.func1({0x26ea090, 0xc0005f48c0}, 0xc000ebde00)
  /home/runner/go/pkg/mod/github.com/getsentry/sentry-go@v0.13.0/http/sentryhttp.go:103 +0x3c3
net/http.HandlerFunc.ServeHTTP(0xc000767380?, {0x26ea090?, 0xc0005f48c0?}, 0xc0009a3800?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d49320, {0x26ea090, 0xc0005f48c0}, 0xc000ebde00)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x355
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x26ea090, 0xc0005f48c0}, 0xc000ebde00)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x1d03dc0?, {0x26ea090?, 0xc0005f48c0?}, 0xc0000db0c5?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc000d492c0, {0x26ea090, 0xc0005f48c0}, 0xc000ebde00)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xc000a08be0?, {0x26ea090?, 0xc0005f48c0?}, 0xc000ebde00?)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/cors.(*Cors).Handler.func1({0x26ea090, 0xc0005f48c0}, 0xc000ebde00)
  /home/runner/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x1bd
net/http.HandlerFunc.ServeHTTP(0x26ec830?, {0x26ea090?, 0xc0005f48c0?}, 0x36331f0?)a
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2109 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d492c0, {0x26ea090, 0xc0005f48c0}, 0xc000ebdd00)
  /home/runner/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x310
github.com/cortezaproject/corteza/server/pkg/api/server.(*demux).ServeHTTP(0x0?, {0x26ea090?, 0xc0005f48c0}, 0xc000ebdd00)
  /home/runner/work/corteza/corteza/server/pkg/api/server/demux.go:51 +0x113
net/http.serverHandler.ServeHTTP({0x26e3fe8?}, {0x26ea090, 0xc0005f48c0}, 0xc000ebdd00)
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0009a54a0, {0x26ec8d8, 0xc000432210})
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
  /opt/hostedtoolcache/go/1.19.3/x64/src/net/http/server.go:3102 +0x4db
================================================================================
```

**Comment by skamensky** [comment]
I figured out the issue.

1. You need to add a datasource and save the report page before adding a ui element. That was the cause of the server panic
2. The client is trying to download the entire report which is 200MB (and then probably doing transformations on the response). Is there any way the client can do some pagination instead of downloading the whole report?

![image](https://user-images.githubusercontent.com/19151369/212392878-cefbbe97-5d34-47c0-8274-b3dd2b312bea.png)
